-- =============================================================================
-- ANTARCTIC NAVIGATION DECISION SUPPORT SYSTEM
-- Master Database Schema for Supabase (PostgreSQL + PostGIS)
-- Run this script in your Supabase SQL Editor:
-- https://supabase.com/dashboard/project/hbvutrfkcyduzlatmueg/sql/new
-- =============================================================================

-- 1. Enable Required Extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "postgis";

-- 2. User Profiles Table (Linked to Supabase Auth)
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    full_name TEXT,
    organization TEXT,
    role TEXT DEFAULT 'operator',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Trigger to automatically populate profile when a user signs up via Supabase Auth
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.profiles (id, full_name, organization, role)
    VALUES (
        NEW.id,
        COALESCE(NEW.raw_user_meta_data->>'full_name', 'Polar Expedition Operator'),
        COALESCE(NEW.raw_user_meta_data->>'organization', 'Antarctic Research Institute'),
        COALESCE(NEW.raw_user_meta_data->>'role', 'operator')
    )
    ON CONFLICT (id) DO NOTHING;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Trigger function for updated_at timestamps
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 3. Vessels Table (Fleet Assets)
CREATE TABLE IF NOT EXISTS public.vessels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID,
    vessel_name TEXT NOT NULL,
    registration_number TEXT,
    imo_number TEXT,
    call_sign TEXT,
    vessel_type TEXT DEFAULT 'Research Vessel',
    owner_name TEXT,

    latitude DOUBLE PRECISION NOT NULL CHECK (latitude BETWEEN -90.0 AND 90.0),
    longitude DOUBLE PRECISION NOT NULL CHECK (longitude BETWEEN -180.0 AND 180.0),
    location GEOGRAPHY(Point, 4326) GENERATED ALWAYS AS (ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)::geography) STORED,

    destination_latitude DOUBLE PRECISION CHECK (destination_latitude IS NULL OR (destination_latitude BETWEEN -90.0 AND 90.0)),
    destination_longitude DOUBLE PRECISION CHECK (destination_longitude IS NULL OR (destination_longitude BETWEEN -180.0 AND 180.0)),
    destination TEXT,

    max_speed DOUBLE PRECISION NOT NULL CHECK (max_speed > 0),
    normal_speed DOUBLE PRECISION NOT NULL CHECK (normal_speed > 0),
    fuel_consumption_rate DOUBLE PRECISION NOT NULL CHECK (fuel_consumption_rate > 0),
    fuel_capacity DOUBLE PRECISION NOT NULL CHECK (fuel_capacity > 0),
    ice_class TEXT NOT NULL DEFAULT 'PC3',

    status TEXT NOT NULL DEFAULT 'OPERATIONAL',

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

DROP TRIGGER IF EXISTS tr_vessels_updated_at ON public.vessels;
CREATE TRIGGER tr_vessels_updated_at
    BEFORE UPDATE ON public.vessels
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- 4. Environmental Data Tables
CREATE TABLE IF NOT EXISTS public.sea_ice_observations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    latitude DOUBLE PRECISION NOT NULL CHECK (latitude BETWEEN -90.0 AND 90.0),
    longitude DOUBLE PRECISION NOT NULL CHECK (longitude BETWEEN -180.0 AND 180.0),
    location GEOGRAPHY(Point, 4326) GENERATED ALWAYS AS (ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)::geography) STORED,
    observation_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ice_concentration DOUBLE PRECISION NOT NULL CHECK (ice_concentration BETWEEN 0.0 AND 100.0),
    ice_extent DOUBLE PRECISION,
    surface_temperature DOUBLE PRECISION,
    source TEXT DEFAULT 'DEMO_SYNTHETIC',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.icebergs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id TEXT UNIQUE NOT NULL,
    latitude DOUBLE PRECISION NOT NULL CHECK (latitude BETWEEN -90.0 AND 90.0),
    longitude DOUBLE PRECISION NOT NULL CHECK (longitude BETWEEN -180.0 AND 180.0),
    location GEOGRAPHY(Point, 4326) GENERATED ALWAYS AS (ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)::geography) STORED,
    observation_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    length DOUBLE PRECISION DEFAULT 500.0,
    width DOUBLE PRECISION DEFAULT 250.0,
    height DOUBLE PRECISION DEFAULT 40.0,
    speed DOUBLE PRECISION DEFAULT 1.0,
    direction DOUBLE PRECISION DEFAULT 0.0,
    source TEXT DEFAULT 'DEMO_SYNTHETIC',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

DROP TRIGGER IF EXISTS tr_icebergs_updated_at ON public.icebergs;
CREATE TRIGGER tr_icebergs_updated_at
    BEFORE UPDATE ON public.icebergs
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE IF NOT EXISTS public.weather_observations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    latitude DOUBLE PRECISION NOT NULL CHECK (latitude BETWEEN -90.0 AND 90.0),
    longitude DOUBLE PRECISION NOT NULL CHECK (longitude BETWEEN -180.0 AND 180.0),
    observation_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    temperature DOUBLE PRECISION NOT NULL,
    wind_speed DOUBLE PRECISION NOT NULL,
    wind_direction DOUBLE PRECISION NOT NULL,
    pressure DOUBLE PRECISION DEFAULT 985.0,
    precipitation DOUBLE PRECISION DEFAULT 0.0,
    wave_height DOUBLE PRECISION DEFAULT 2.0,
    source TEXT DEFAULT 'DEMO_SYNTHETIC',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.ocean_observations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    latitude DOUBLE PRECISION NOT NULL CHECK (latitude BETWEEN -90.0 AND 90.0),
    longitude DOUBLE PRECISION NOT NULL CHECK (longitude BETWEEN -180.0 AND 180.0),
    observation_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    water_temperature DOUBLE PRECISION NOT NULL,
    current_speed DOUBLE PRECISION NOT NULL,
    current_direction DOUBLE PRECISION NOT NULL,
    wave_height DOUBLE PRECISION DEFAULT 2.0,
    source TEXT DEFAULT 'DEMO_SYNTHETIC',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 5. AI/ML Predictions Persistence Tables
CREATE TABLE IF NOT EXISTS public.sea_ice_predictions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    latitude DOUBLE PRECISION NOT NULL CHECK (latitude BETWEEN -90.0 AND 90.0),
    longitude DOUBLE PRECISION NOT NULL CHECK (longitude BETWEEN -180.0 AND 180.0),
    location GEOGRAPHY(Point, 4326) GENERATED ALWAYS AS (ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)::geography) STORED,
    prediction_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    target_time TIMESTAMPTZ NOT NULL,
    predicted_concentration DOUBLE PRECISION NOT NULL CHECK (predicted_concentration BETWEEN 0.0 AND 100.0),
    confidence DOUBLE PRECISION DEFAULT 85.0,
    model_version TEXT DEFAULT 'v1.0',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.iceberg_trajectory_predictions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    iceberg_id BIGINT NOT NULL REFERENCES public.icebergs(id) ON DELETE CASCADE,
    prediction_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    target_time TIMESTAMPTZ NOT NULL,
    predicted_latitude DOUBLE PRECISION NOT NULL CHECK (predicted_latitude BETWEEN -90.0 AND 90.0),
    predicted_longitude DOUBLE PRECISION NOT NULL CHECK (predicted_longitude BETWEEN -180.0 AND 180.0),
    location GEOGRAPHY(Point, 4326) GENERATED ALWAYS AS (ST_SetSRID(ST_MakePoint(predicted_longitude, predicted_latitude), 4326)::geography) STORED,
    probability DOUBLE PRECISION DEFAULT 0.85,
    model_version TEXT DEFAULT 'v1.2',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 6. Navigation Routes & Pareto Optimization Results
CREATE TABLE IF NOT EXISTS public.route_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID,
    ship_id BIGINT REFERENCES public.vessels(id) ON DELETE SET NULL,
    start_latitude DOUBLE PRECISION NOT NULL CHECK (start_latitude BETWEEN -90.0 AND 90.0),
    start_longitude DOUBLE PRECISION NOT NULL CHECK (start_longitude BETWEEN -180.0 AND 180.0),
    destination_latitude DOUBLE PRECISION NOT NULL CHECK (destination_latitude BETWEEN -90.0 AND 90.0),
    destination_longitude DOUBLE PRECISION NOT NULL CHECK (destination_longitude BETWEEN -180.0 AND 180.0),
    safety_weight DOUBLE PRECISION DEFAULT 0.7 CHECK (safety_weight BETWEEN 0.0 AND 1.0),
    fuel_weight DOUBLE PRECISION DEFAULT 0.2 CHECK (fuel_weight BETWEEN 0.0 AND 1.0),
    time_weight DOUBLE PRECISION DEFAULT 0.1 CHECK (time_weight BETWEEN 0.0 AND 1.0),
    requested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.route_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_request_id BIGINT NOT NULL REFERENCES public.route_requests(id) ON DELETE CASCADE,
    distance_km DOUBLE PRECISION NOT NULL,
    estimated_time_hours DOUBLE PRECISION NOT NULL,
    estimated_fuel DOUBLE PRECISION NOT NULL,
    safety_score DOUBLE PRECISION NOT NULL,
    overall_risk TEXT DEFAULT 'LOW',
    route_geometry JSONB NOT NULL,
    route_type TEXT DEFAULT 'balanced',
    major_hazards JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 7. Audit Logging
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID,
    entity_type TEXT NOT NULL,
    entity_id TEXT NOT NULL,
    action TEXT NOT NULL,
    old_data JSONB,
    new_data JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 8. Spatial & B-Tree Performance Indexes
CREATE INDEX IF NOT EXISTS idx_vessels_location ON public.vessels USING GIST (location);
CREATE INDEX IF NOT EXISTS idx_vessels_name ON public.vessels (vessel_name);
CREATE INDEX IF NOT EXISTS idx_icebergs_location ON public.icebergs USING GIST (location);
CREATE INDEX IF NOT EXISTS idx_sea_ice_location ON public.sea_ice_observations USING GIST (location);
CREATE INDEX IF NOT EXISTS idx_route_requests_ship ON public.route_requests (ship_id);
CREATE INDEX IF NOT EXISTS idx_route_results_request ON public.route_results (route_request_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON public.audit_logs (created_at DESC);

-- 9. Row-Level Security (RLS) Configuration
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vessels ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sea_ice_observations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.icebergs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.weather_observations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ocean_observations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sea_ice_predictions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.iceberg_trajectory_predictions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.route_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.route_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

-- Clean existing policies to avoid collision
DROP POLICY IF EXISTS "Allow select on vessels" ON public.vessels;
DROP POLICY IF EXISTS "Allow insert on vessels" ON public.vessels;
DROP POLICY IF EXISTS "Allow update on vessels" ON public.vessels;
DROP POLICY IF EXISTS "Allow delete on vessels" ON public.vessels;

-- Vessels Policies (Public Read & Write for fast operator interaction)
CREATE POLICY "Allow select on vessels" ON public.vessels FOR SELECT USING (true);
CREATE POLICY "Allow insert on vessels" ON public.vessels FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow update on vessels" ON public.vessels FOR UPDATE USING (true);
CREATE POLICY "Allow delete on vessels" ON public.vessels FOR DELETE USING (true);

-- Route Requests & Results Policies
DROP POLICY IF EXISTS "Allow all select route_requests" ON public.route_requests;
DROP POLICY IF EXISTS "Allow all insert route_requests" ON public.route_requests;
DROP POLICY IF EXISTS "Allow all select route_results" ON public.route_results;
DROP POLICY IF EXISTS "Allow all insert route_results" ON public.route_results;
CREATE POLICY "Allow all select route_requests" ON public.route_requests FOR SELECT USING (true);
CREATE POLICY "Allow all insert route_requests" ON public.route_requests FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow all select route_results" ON public.route_results FOR SELECT USING (true);
CREATE POLICY "Allow all insert route_results" ON public.route_results FOR INSERT WITH CHECK (true);

-- Environmental & Predictions Policies (Open read access)
DROP POLICY IF EXISTS "Public read sea ice" ON public.sea_ice_observations;
DROP POLICY IF EXISTS "Public read icebergs" ON public.icebergs;
DROP POLICY IF EXISTS "Public read weather" ON public.weather_observations;
DROP POLICY IF EXISTS "Public read ocean" ON public.ocean_observations;
DROP POLICY IF EXISTS "Public read sea ice pred" ON public.sea_ice_predictions;
DROP POLICY IF EXISTS "Public read iceberg pred" ON public.iceberg_trajectory_predictions;

CREATE POLICY "Public read sea ice" ON public.sea_ice_observations FOR SELECT USING (true);
CREATE POLICY "Public read icebergs" ON public.icebergs FOR SELECT USING (true);
CREATE POLICY "Public read weather" ON public.weather_observations FOR SELECT USING (true);
CREATE POLICY "Public read ocean" ON public.ocean_observations FOR SELECT USING (true);
CREATE POLICY "Public read sea ice pred" ON public.sea_ice_predictions FOR SELECT USING (true);
CREATE POLICY "Public read iceberg pred" ON public.iceberg_trajectory_predictions FOR SELECT USING (true);

-- Audit log policies
DROP POLICY IF EXISTS "Public insert audit" ON public.audit_logs;
DROP POLICY IF EXISTS "Public select audit" ON public.audit_logs;
CREATE POLICY "Public insert audit" ON public.audit_logs FOR INSERT WITH CHECK (true);
CREATE POLICY "Public select audit" ON public.audit_logs FOR SELECT USING (true);

-- 10. Initial Seed Fleet & Data
INSERT INTO public.vessels (
    vessel_name, registration_number, imo_number, call_sign, vessel_type, owner_name,
    latitude, longitude, destination_latitude, destination_longitude, destination,
    max_speed, normal_speed, fuel_consumption_rate, fuel_capacity, ice_class, status
) VALUES
(
    'RRS Sir David Attenborough', 'UK-POLAR-01', '9798222', 'ZDLP7', 'Polar Research Vessel', 'British Antarctic Survey',
    -64.82, -58.25, -67.57, -68.13, 'Rothera Research Station',
    17.5, 13.0, 78.0, 1150000.0, 'PC4', 'OPERATIONAL'
),
(
    'RV Polarstern', 'GER-POLAR-02', '8013132', 'DBLK', 'Icebreaker & Research Vessel', 'Alfred Wegener Institute',
    -70.50, -45.00, -75.00, -26.00, 'Neumayer Station III',
    16.0, 11.5, 92.0, 1400000.0, 'PC3', 'OPERATIONAL'
),
(
    'RV Nathaniel B. Palmer', 'USA-POLAR-03', '9007295', 'WBP3210', 'Antarctic Research Vessel', 'National Science Foundation',
    -63.50, -60.00, -64.77, -64.05, 'Palmer Station',
    15.0, 11.0, 84.0, 980000.0, 'PC5', 'OPERATIONAL'
)
ON CONFLICT DO NOTHING;

INSERT INTO public.icebergs (
    external_id, latitude, longitude, observation_time, length, width, height, speed, direction, source
) VALUES
('A-68A', -63.15, -56.80, NOW(), 1200.0, 600.0, 48.0, 1.4, 45.0, 'BYU_NIC_TRACKING'),
('A-74', -71.20, -25.50, NOW(), 850.0, 420.0, 35.0, 0.9, 120.0, 'BYU_NIC_TRACKING'),
('B-15J', -66.80, 140.20, NOW(), 650.0, 310.0, 28.0, 1.1, 210.0, 'BYU_NIC_TRACKING')
ON CONFLICT (external_id) DO NOTHING;
