-- 003_vessels.sql: Vessels table with geospatial location and constraints
CREATE TABLE IF NOT EXISTS public.vessels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    vessel_name TEXT NOT NULL,
    registration_number TEXT,
    imo_number TEXT,
    call_sign TEXT,
    vessel_type TEXT DEFAULT 'Research Vessel',
    owner_name TEXT,

    latitude DOUBLE PRECISION NOT NULL CHECK (latitude BETWEEN -90.0 AND 90.0),
    longitude DOUBLE PRECISION NOT NULL CHECK (longitude BETWEEN -180.0 AND 180.0),
    location GEOGRAPHY(Point, 4326) GENERATED ALWAYS AS (ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)::geography) STORED,

    destination_latitude DOUBLE PRECISION CHECK (destination_latitude IS NULL OR (destination_latitude BETWEEN -90.0 AND 90.0)),
    destination_longitude DOUBLE PRECISION CHECK (destination_longitude IS NULL OR (destination_longitude BETWEEN -180.0 AND 180.0)),
    destination TEXT,

    max_speed DOUBLE PRECISION NOT NULL CHECK (max_speed > 0),
    normal_speed DOUBLE PRECISION NOT NULL CHECK (normal_speed > 0),
    fuel_consumption_rate DOUBLE PRECISION NOT NULL CHECK (fuel_consumption_rate > 0),
    fuel_capacity DOUBLE PRECISION NOT NULL CHECK (fuel_capacity > 0),
    ice_class TEXT NOT NULL DEFAULT 'PC3',

    status TEXT NOT NULL DEFAULT 'OPERATIONAL',

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Trigger to auto-update updated_at timestamp on vessels
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS tr_vessels_updated_at ON public.vessels;
CREATE TRIGGER tr_vessels_updated_at
    BEFORE UPDATE ON public.vessels
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
