-- 004_environmental_data.sql: Sea ice observations, icebergs, weather, and ocean observations
CREATE TABLE IF NOT EXISTS public.sea_ice_observations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    latitude DOUBLE PRECISION NOT NULL CHECK (latitude BETWEEN -90.0 AND 90.0),
    longitude DOUBLE PRECISION NOT NULL CHECK (longitude BETWEEN -180.0 AND 180.0),
    location GEOGRAPHY(Point, 4326) GENERATED ALWAYS AS (ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)::geography) STORED,
    observation_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ice_concentration DOUBLE PRECISION NOT NULL CHECK (ice_concentration BETWEEN 0.0 AND 100.0),
    ice_extent DOUBLE PRECISION,
    surface_temperature DOUBLE PRECISION,
    source TEXT DEFAULT 'DEMO_SYNTHETIC',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.icebergs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id TEXT UNIQUE NOT NULL,
    latitude DOUBLE PRECISION NOT NULL CHECK (latitude BETWEEN -90.0 AND 90.0),
    longitude DOUBLE PRECISION NOT NULL CHECK (longitude BETWEEN -180.0 AND 180.0),
    location GEOGRAPHY(Point, 4326) GENERATED ALWAYS AS (ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)::geography) STORED,
    observation_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    length DOUBLE PRECISION DEFAULT 500.0,
    width DOUBLE PRECISION DEFAULT 250.0,
    height DOUBLE PRECISION DEFAULT 40.0,
    speed DOUBLE PRECISION DEFAULT 1.0,
    direction DOUBLE PRECISION DEFAULT 0.0,
    source TEXT DEFAULT 'DEMO_SYNTHETIC',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

DROP TRIGGER IF EXISTS tr_icebergs_updated_at ON public.icebergs;
CREATE TRIGGER tr_icebergs_updated_at
    BEFORE UPDATE ON public.icebergs
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE IF NOT EXISTS public.weather_observations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    latitude DOUBLE PRECISION NOT NULL CHECK (latitude BETWEEN -90.0 AND 90.0),
    longitude DOUBLE PRECISION NOT NULL CHECK (longitude BETWEEN -180.0 AND 180.0),
    observation_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    temperature DOUBLE PRECISION NOT NULL,
    wind_speed DOUBLE PRECISION NOT NULL,
    wind_direction DOUBLE PRECISION NOT NULL,
    pressure DOUBLE PRECISION DEFAULT 985.0,
    precipitation DOUBLE PRECISION DEFAULT 0.0,
    wave_height DOUBLE PRECISION DEFAULT 2.0,
    source TEXT DEFAULT 'DEMO_SYNTHETIC',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.ocean_observations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    latitude DOUBLE PRECISION NOT NULL CHECK (latitude BETWEEN -90.0 AND 90.0),
    longitude DOUBLE PRECISION NOT NULL CHECK (longitude BETWEEN -180.0 AND 180.0),
    observation_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    water_temperature DOUBLE PRECISION NOT NULL,
    current_speed DOUBLE PRECISION NOT NULL,
    current_direction DOUBLE PRECISION NOT NULL,
    wave_height DOUBLE PRECISION DEFAULT 2.0,
    source TEXT DEFAULT 'DEMO_SYNTHETIC',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
