-- 006_routes.sql: Route requests and generated route results
CREATE TABLE IF NOT EXISTS public.route_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    ship_id BIGINT REFERENCES public.vessels(id) ON DELETE SET NULL,
    start_latitude DOUBLE PRECISION NOT NULL CHECK (start_latitude BETWEEN -90.0 AND 90.0),
    start_longitude DOUBLE PRECISION NOT NULL CHECK (start_longitude BETWEEN -180.0 AND 180.0),
    destination_latitude DOUBLE PRECISION NOT NULL CHECK (destination_latitude BETWEEN -90.0 AND 90.0),
    destination_longitude DOUBLE PRECISION NOT NULL CHECK (destination_longitude BETWEEN -180.0 AND 180.0),
    safety_weight DOUBLE PRECISION DEFAULT 0.7 CHECK (safety_weight BETWEEN 0.0 AND 1.0),
    fuel_weight DOUBLE PRECISION DEFAULT 0.2 CHECK (fuel_weight BETWEEN 0.0 AND 1.0),
    time_weight DOUBLE PRECISION DEFAULT 0.1 CHECK (time_weight BETWEEN 0.0 AND 1.0),
    requested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.route_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_request_id BIGINT NOT NULL REFERENCES public.route_requests(id) ON DELETE CASCADE,
    distance_km DOUBLE PRECISION NOT NULL,
    estimated_time_hours DOUBLE PRECISION NOT NULL,
    estimated_fuel DOUBLE PRECISION NOT NULL,
    safety_score DOUBLE PRECISION NOT NULL,
    overall_risk TEXT DEFAULT 'LOW',
    route_geometry JSONB NOT NULL,
    route_type TEXT DEFAULT 'balanced',
    major_hazards JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
